### ISSUE TITLE
Saving results as txt, program crashed

### ISSUE THREAD

**Issue by jonasol** [CSMarkBenchmark/CSMark#10]
**CSMark version used**
0.17.0
**OS used**
Windows 10 Pro : 10.0.15063 Build 15063 
**Bug / feature**
Saving the results as txt.file after end results has been done.
**How to reproduce error**
Save end result as txt.file

**Error message**
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CSMarkLib.BenchmarkManagement.CommandProcessor.handleSaveDialog(String saveConfirm, String CSMarkVersion) in D:\Documents\GitHub\CSMarkLib\CSMarkLib\CommandProcessor.cs:line 147
   at CSMarkRedux.Program.Main(String[] args) in D:\Documents\GitHub\CSMark\CSMarkRedux\Program.cs:line 279

**Comment by AluminiumTech** [comment]
@jonasol 
Did you install the program using the .exe ?

And if so, did you run the program as an Admin?

**Comment by jonasol** [comment]
@AluminiumTech Installed using .exe, did not run the program as admin.

**Comment by AluminiumTech** [comment]
@jonasol  Could you try re-running the program as Admin and describe if anything else happens?

Thanks.

**Comment by AluminiumTech** [comment]
And could you try to do reproduce the bug using the portable zip file?

**Comment by AluminiumTech** [comment]
Conducted testing using Win10-x64 zip file as well as the exe files. 

It appears to be a permissions issue.

In 0.18.0, I will add a reminder for users who used the installer to run as Administrator if they wish to save the file.
