### ISSUE TITLE
CSMark 0.20.0 doesn't prompt user for first time setup on Linux

### ISSUE THREAD

**Issue by AluminiumTech** [CSMarkBenchmark/CSMark#16]
* CSMark 0.20.0 was used
* Device was running Ubuntu 17.04 with latest updates
* Bug: Starting CSMark for the first time does not prompt CSMark to configure language files on Linux
* Install CSMark on Linux and attempt to run it.

**Comment by AluminiumTech** [comment]
Unable to replicate bug on Windows. 

Will attempt to replicate the bug in 0.22.0 on Ubuntu 17.10

**Comment by owluitar** [comment]
Similar behavior on CSMark 0.22.2 on CentOS 7

```
The configuration file was saved at ... /home/USER/linux-64/publish\Config\
Locale Detection took a long time to respond. Applying Correct Locales.
```

It made the configuration file but outside the publish folder and with backslashes?

**Comment by AluminiumTech** [comment]
> It made the configuration file but outside the publish folder and with backslashes?

This'll be fixed potentially in 0.22.4. I'm also adding a lot more Exception handling to provide errors when things go wrong (Currently the usage of Exceptions are somewhat limited). 

But before I release 0.22.4, I'll need to know how Macs handle 0.22.3 so I can adjust it accordingly.

**Comment by owluitar** [comment]
CSMark 0.22.3 on CentOS 7 brought up the first time configuration.

This time, it says,

```
The Configuration file was not able to be saved. Here's some details in case you need them:
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/USER/linux-x64/publish\Config\/CSMark_Config.txt'.

at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func 2 errorRewriter)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at SystemIO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
At System.IO.StreamWriter..ctor(String path, Boolean append)
at System.IO.File.CreateText(String path)
at CSMarkRedux.Configuration.createSettingsFile(String locale, String language) in C:\Users\alast\Documents\GitHub\CSMark\CSMarkRedux\Configuration.cs:line 63
```

**Comment by AluminiumTech** [comment]
Oh ok. I'll try to fix that.

**Comment by AluminiumTech** [comment]
I've made some changes so that the by default it uses English as the language and setup no longer requires human intervention other than re-starting CSMark once setup is done.

This should appear in CSMark 0.22.4
