### ISSUE TITLE
Norwegian translations for CSMark

### ISSUE THREAD

**Issue by AluminiumTech** [CSMarkBenchmark/CSMark#19]
Translations for CSMark....

Open Source Edition -> ?
of System Memory -> ?
To find out what Processes may be harming your score, please enter the "process" command. -> ?
OS Architecture: -> ?
AutoUpdaterNetStandard Version: -> ?
Please enter the amount of calculations you'd like to be performed in millions: -> ?
Failed to set the custom amount of calculations. -> ?
A new update for CSMark is available! -> ?
The changelog for the latest version can be found here: -> ?
To download the update, go to this URL: -> ?
Checking for updates failed. Proceeding to start CSMark. -> ?
Installed CSMark Version: -> ?
Latest CSMark Version: -> ?
Experienced networking issues whilst checking for updates. -> ?
Checking for updates to CSMark. This should just take a moment. -> ?
milliseconds to check for updates. -> ?
Took -> ?
This product is up to date. -> ?
Process -> ?
To run the test with a specific amount of calculations, please enter -> ?
Please give feedback, or report bugs by opening a GitHub issue at https://github.com/CSMarkBenchmark/CSMark/issues/new-> ?
0 -> ?
1 -> ?
2 -> ?
3 -> ?
To run the multi tasking tests only, please enter -> ?
To run the single threaded and multi threaded tests, please enter -> ?
To run the single threaded tests only, please enter -> ?
To run the stress test utility, please enter -> ?
About -> ?
_Calc -> ?
Clear -> ?
Help -> ?
Exit -> ?
That's not a command supported by CSMark! Please enter a supported command. -> ?
List of supported commands: -> ?
For more information on what these commands do, please go to: -> ?
VERSION -> ?
Are you sure you want to Exit CSMark? -> ?
Would you like to save the results to a Text File? -> ?
CSMarkLib Version: -> ?
CSMark RunTime Identifier: -> ?
CSMark Version: -> ?
Don't turn off your Device. -> ? 
CSMark is using -> ?
OS ID: -> ?
List of processes running on this PC currently: -> ?
Hours -> ?
Minutes -> ?
Seconds -> ?
Milliseconds -> ?
NO -> ?
YES -> ?
Please enter YES or NO. -> ?
The text file could not be saved. -> ?
Starting CSMark. -> ?
BREAK -> ?
STOP -> ?
Starting stress test. -> ?
To stop the stress test, please exit the program or enter STOP or BREAK -> ?
Are you sure you want to run the stress test for -> ?
This will take several minutes. -> ?
Starting Tests... -> ?
Do you want to run a timed Stress Test? -> ?
How many -> ?
would you like the stress test to run for? -> ?
CSMark -> ?
For Support Status, go to https://github.com/CSMarkBenchmark/CSMark/blob/master/Support.md -> ?
Welcome to CSMark Open Source Edition. -> ?
Warning: CSMark has detected a large amount of processes are running on your PC. For the best performance possible, reduce the amount of background processes running. -> ?

1/2

**Comment by AluminiumTech** [comment]
Copyright (C) 2017 AluminiumTech
This product is licensed under the GNU General Public License (GPL) v3 open source license.

This is free software (As defined at https://www.gnu.org/philosophy/free-sw.html) :
you can re-distribute it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation.

This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.
If not, see http://www.gnu.org/licenses/
To learn more about the GPL v3 license, go to http://www.gnu.org/licenses/  -> ?

2/2

**Comment by PandaWithBandana** [comment]
Translations for CSMark....
Translations by: Henry (discord: henry#2600)


Open Source Edition -> Åpen kildeutgave
of System Memory -> av Systemminne
To find out what Processes may be harming your score, please enter the "process" command. -> For å finne ut hvilke prosesser som kan ødelegge for det endelige resultatet, skriv "process" kommandoen.
OS Architecture: -> OS Arkitektur:
AutoUpdaterNetStandard Version: -> AutoUpdaterNetStandard Versjon:
Please enter the amount of calculations you'd like to be performed in millions: -> Vennligst skriv inn ønsket antall of kalkuleringer du vil skal bli utført iløpet av millisekunder.
Failed to set the custom amount of calculations. -> Feilet med å sette et egendefinert antall kalkuleringer. 
A new update for CSMark is available! -> En ny oppdatering for CSMark er tilgjengelig!
The changelog for the latest version can be found here: -> Endringsloggen for den siste utgitte versjonen kan bli funnet her:
To download the update, go to this URL: -> For å laste ned oppdateringen gå til denne lenken:
Checking for updates failed. Proceeding to start CSMark. -> Oppdateringssøk feilet. Starter opp CSMark.
Installed CSMark Version: -> Installerte CSMark versjon:
Latest CSMark Version: -> Siste CSMark versjon:
Experienced networking issues whilst checking for updates. -> CSMark opplevde internett feil mens den sjekket for oppdateringer.
Checking for updates to CSMark. This should just take a moment. -> Sjekker om det er mulige oppdateringer for CSMark. Dette vil bare ta et øyeblikk.
milliseconds to check for updates. -> millisekunder for å sjekke oppdateringer.
Took -> Tok
This product is up to date. -> Dette programmet er allerede oppdatert.
Process -> Prosess
To run the test with a specific amount of calculations, please enter -> For å kjøre denne testen med en spesifikk mengde kalkuleringer, vennligst skriv
Please give feedback, or report bugs by opening a GitHub issue at https://github.com/CSMarkBenchmark/CSMark/issues/new-> Vennligst gi tilbakemelding eller rapporter feil på vår GitHub side: https://github.com/CSMarkBenchmark/CSMark/issues/new-
0 -> Null
1 -> En
2 -> To
3 -> Tre
To run the multi tasking tests only, please enter -> For å kjøre multi threaded tester, vennligst skriv
To run the single threaded and multi threaded tests, please enter -> For å kjøre single threaded og multi threaded tester, vennligst skriv
To run the single threaded tests only, please enter -> For å kjøre single theaded test, vennligst skriv
To run the stress test utility, please enter -> For å kjøre stress test nytte, vennligst skriv
About -> Om
_Calc -> _Kalk
Clear -> Rens
Help -> Hjelp
Exit -> Lukk
That's not a command supported by CSMark! Please enter a supported command. -> Denne kommandoen er ikke støttet av CSMark. Vennligst skriv inn en støttet kommando!
List of supported commands: -> Liste over støttede kommandoer:
For more information on what these commands do, please go to: -> For mer informasjon angående hva disse kommandoene gjøre, gå til:
VERSION -> VERSJON
Are you sure you want to Exit CSMark? -> Er du sikker på at du vil lukke CSMark?
Would you like to save the results to a Text File? -> Vil du lagre resultatene i en tekst fil?
CSMarkLib Version: -> CSMarkLib Versjon
CSMark RunTime Identifier: -> CSMark RunTime Identifiserer
CSMark Version: -> CSMark versjon
Don't turn off your Device. -> Ikke skru av enheten din
CSMark is using -> CSMark bruker
OS ID: -> OS ID: (it's the same)
List of processes running on this PC currently: -> Liste over prosesser som for øyeblikket kjører:
Hours -> Timer
Minutes -> Minutter
Seconds -> Sekunder
Milliseconds -> Millisekunder
NO -> Nei
YES -> Ja
Please enter YES or NO. -> Vennligst trykk JA eller NEI
The text file could not be saved. -> Textfilen kunne ikke bli lagret.
Starting CSMark. -> Starter CSMark
BREAK -> PAUSE
STOP -> STOPP
Starting stress test. -> Starter stress test
To stop the stress test, please exit the program or enter STOP or BREAK -> For å stoppe stress testen, vennligst lukk programmet eller klikk STOP eller PAUSE
Are you sure you want to run the stress test for -> Er du sikker på at du vil kjøre stress testen for
This will take several minutes. -> Dette vil ta et par minutter.
Starting Tests... -> Starter tester...
Do you want to run a timed Stress Test? -> Vil du kjøre en tidplanlagt stress test?
How many -> Hvor mange?
would you like the stress test to run for? -> Vil at stress testen skal kjøre?
CSMark -> CSMark (bruh, its the same :D)
For Support Status, go to https://github.com/CSMarkBenchmark/CSMark/blob/master/Support.md -> For support status, gå til https://github.com/CSMarkBenchmark/CSMark/blob/master/Support.md
Welcome to CSMark Open Source Edition. -> Velkommen til CSMARK åpen kildeutgave.
Warning: CSMark has detected a large amount of processes are running on your PC. For the best performance possible, reduce the amount of background processes running. -> Advarsel! CSMARK har oppdaget en stor mengde av prosesser som kjører på din PC. For best ytelse reduser antall bakgrunnsprogrammer som kjører.

ALL OF THE TEXT BELOW IS THE SAME IN NORWEGIAN!

Copyright (C) 2017 AluminiumTech
This product is licensed under the GNU General Public License (GPL) v3 open source license.

This is free software (As defined at https://www.gnu.org/philosophy/free-sw.html) :
you can re-distribute it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation.

This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.
If not, see http://www.gnu.org/licenses/
To learn more about the GPL v3 license, go to http://www.gnu.org/licenses/ -> For å lære mer om GPL v3 lisenser, gå til http://www.gnu.org/licenses/

**Comment by AluminiumTech** [comment]
Thanks much. Added all of those translations

**Comment by AluminiumTech** [comment]
I've got a few more for 0.23.0

You are receiving updates from the Stable Release Channel -> ?
You are receiving updates from the Beta Release Channel -> ?
You are receiving updates from the Alpha Release Channel -> ?
To receive updates from the Beta Release Channel, enter: -> ?
To receive updates from the Alpha Release Channel, enter: -> ?
To receive updates from the Stable Release Channel, enter: -> ?
beta_update -> ?
stable_update -> ?
alpha _update -> ?

**Comment by AluminiumTech** [comment]
Terminating the application -> ?

**Comment by AluminiumTech** [comment]
Stable Release Channel -> ?
Beta Release Channel -> ?
Alpha Release Channel -> ?

**Comment by PandaWithBandana** [comment]
0.23.0 TRANSLATIONS:

You are receiving updates from the Stable Release Channel -> Du mottar nå oppdateringer fra Stable lanseringer.
You are receiving updates from the Beta Release Channel -> Du mottar nå oppdateringer fra Beta lanseringer.
You are receiving updates from the Alpha Release Channel -> Du mottar nå oppdateringer fra Alpha lanseringer.
To receive updates from the Beta Release Channel, enter: -> For å motta oppdateringer fra Beta lanseringer, skriv:
To receive updates from the Alpha Release Channel, enter: -> For å motta oppdateringer fra Alpha lanseringer, skriv:
To receive updates from the Stable Release Channel, enter: -> For å motta oppdateringer fra Stable lanseringer, skriv:
beta_update -> beta_oppdatering
stable_update -> stable_oppdatering
alpha _update -> alpha_oppdatering
Terminating the application -> Avslutt applikasjonen
Stable Release Channel -> Stable lanseringer
Beta Release Channel -> Beta lanseringer
Alpha Release Channel -> Alpha lanseringer

**Comment by AluminiumTech** [comment]
Credits -> ?
Lead Developer -> ?
Developer -> ?
Community Code Contributions -> ?
Community Translations -> ?
provided by -> ?

**Comment by AluminiumTech** [comment]
To change language, enter 4 -> ?
Please select the language you wish to use -> ?
English -> ?
French -> ?
Successfully updated language settings in the Configuration file. Please re-start to apply language changes -> ?

**Comment by AluminiumTech** [comment]
We ran into some issues. Here are the details of the error in case you need it: -> ?
Locale Detection took a long time to respond. Applying correct Locales. -> ?
Locale Detection didn't respond in time. Falling back to English as default. -> ?

**Comment by AluminiumTech** [comment]
January -> ?
February -? ?
March -> ?
April -> ?
May -> ?
June -> ?
July -> ?
August -> ?
September -> ?
October -> ?
November -> ?
December -> ?

**Comment by AluminiumTech** [comment]
Please give feedback, or report bugs by posting an issue on the CSMark Forums at https://forum.csmarkbenchmark.com  -> ?

**Comment by AluminiumTech** [comment]
Closed as Contributor no longer actively contributing translations.
