### ISSUE TITLE
Can't get past Configuration creation in CSMark on Ubuntu 17.10

### ISSUE THREAD

**Issue by AluminiumTech** [CSMarkBenchmark/CSMark#22]
Make sure that this issue satisfies all the criteria below.

* CSMark 0.24.0 was used.
* Running Ubuntu 17.10 64 Bit.
* The configuration folder and file would not be created and errors would be printed
* Start CSMark 0.24.0 on Linux to reproduce the bug.

![error2](https://user-images.githubusercontent.com/14107316/33309583-776a1396-d416-11e7-925b-0b2efebb0405.png)
![errorr1](https://user-images.githubusercontent.com/14107316/33309584-778fdba8-d416-11e7-8d90-797e55cd8003.png)

**Comment by owluitar** [comment]
On CSMark 0.24.0 on CentOS 7, similar error occurs, but after "mkdir Config" in the folder, everything works perfectly.

**Comment by AluminiumTech** [comment]
> On CSMark 0.24.0 on CentOS 7, similar error occurs, but after "mkdir Config" in the folder, everything works perfectly.

I'm guessing that CSMark fails to create the Config directory when on Linux.

**Comment by AluminiumTech** [comment]
It appears that the Config folder is not created on Linux and macOS.

This has been fixed and will be in 0.25.0
