### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by TheMCTipers** [CSMarkBenchmark/CSMark#6]
Windows 10 x86_64
CSMark 0.14.0
--

Suggestion: 
Have a readme inside /win10-x64/win10-x64/, say if you are unable to run CSMarkRedux.exe in /win10-x64/win10-x64/, goto CSMarkRedux.exe in /win10-x64/win10-x64/publish

Add a spacer inbetween where the user inputs text and the text iself:
Welcome to CSMark.
The current time is 2017-08-20 10:14:19 AM
To check for updates, go to https://www.github.com/AluminiumTech/CSMark/releases/
For Support Status, go to https://github.com/AluminiumTech/CSMark/blob/master/Support.MD

To run the single threaded and multi threaded tests, please enter BENCH.
To run the single threaded tests only, please enter BENCH_SINGLE.
To run the multi threaded tests only, please enter BENCH_MULTI.
To run the stress test utility, please enter STRESS_TEST.
To run the stress test utility for a set amount of time, please enter STRESS_TIMED.
Please give feedback, or report bugs by opening a GitHub issue at https://github.com/AluminiumTech/CSMark/issues/new
(SPACER)
(SPACER)

Have a nicer selection screen instead of typing it out:
Welcome to CSMark.
The current time is 2017-08-20 10:14:19 AM
To check for updates, go to https://www.github.com/AluminiumTech/CSMark/releases/
For Support Status, go to https://github.com/AluminiumTech/CSMark/blob/master/Support.MD

To run the single threaded and multi threaded tests, please select BENCH.
To run the single threaded tests only, please select BENCH_SINGLE.
To run the multi threaded tests only, please select BENCH_MULTI.
To run the stress test utility, please select STRESS_TEST.
To run the stress test utility for a set amount of time, please select STRESS_TIMED.
Please give feedback, or report bugs by opening a GitHub issue at https://github.com/AluminiumTech/CSMark/issues/new
(spacer)
(spacer)
>                Benchmark               <
> Benchmark (Single Threaded) <
>  Benchmark (Multi Threaded)  <
>                Stress Test                 <

Have it start at benchmark, and have the text and > < bolded to signify that it is the item that is currently selected. To start, press enter.

Colour code the results. Do it by if it is single or multi, the alogirthm, and the score.
Example:
(Yellow) Single Threaded
(White) Potato Counting | (Green) 938 Potatoes | 
(Blue)   Potato Eating      | (Red) 39 Potatoes       |
---------------
(Pink) Multi Threaded:
(White) Potato Counting | (Green) 3000 Potatoes |
(Blue)    Potato Eating     | (Red) 9377727 Potatoes |

Have the results be in a nice table, or well make it look nicer. Reduce redundant information:
Instead of saying algorithm single threaded, say algorithm only. The information for if it is single or multi threaded will be above in the header. Also say the amount of time per algorithm calculation in the header. 
Example:
Single threaded (By the full potato)
Potato Counting | 938
Potato Eating      | 39
Have the alrgorithm and score nice like in excel or something

![image](https://user-images.githubusercontent.com/29156543/29495800-36fc2cfc-8594-11e7-9b0b-5386a51eee4e.png)

Merge stress testing and stress testing with time.
Have it go:
Do you want to make this stress test timed?
> Yes <
> No <

If no, run forever.
If yes, then get the user to input how long they want to do it in the format:
H : M : S
Hours, minutes, seconds.
1:38:49 for example.

**Comment by AluminiumTech** [comment]
> > Colour code the results. Do it by if it is single or multi, the alogirthm, and the score.
> Example:
> (Yellow) Single Threaded
> (White) Potato Counting | (Green) 938 Potatoes |
> (Blue) Potato Eating | (Red) 39 Potatoes |

Alright, this should be pretty easy to do. And some of it is a regression from 0.13 branch.

This will probably be added alongside the ability to configure CSMark using a text file and a configuration management system.

> Have a nicer selection screen instead of typing it out:
This is not possibly to do easily on Console Applications. The UWP version of CSMark (coming sometime in the future) should have an easier way to choose what you want to do.

> Have the results be in a nice table, or well make it look nicer. Reduce redundant information:
I could look into having CSMark generate a HTML page with the results formatted into a table and then put the file in the results file directory.

>  Reduce redundant information:
I can definitely look into that.

> Merge stress testing and stress testing with time.
Have it go:
Do you want to make this stress test timed?
This would also be pretty easy to implement.

> If yes, then get the user to input how long they want to do it in the format:
> H : M : S
This could be slightly more difficult to implement. I can't guarantee that it'll be added in a future release.

**Comment by AluminiumTech** [comment]
Implemented Line spacing in the upcoming 0.14.1 release.

**Comment by TheMCTipers** [comment]
Instead of having it typed out or my idea of a selection screen, you could have the user type out a number instead, makes it slightly easier and feel less cryptic.

You could have CSMark open up that HTML file automagically through Windows 10 and its preferred web browser.

**Comment by AluminiumTech** [comment]
> Instead of having it typed out or my idea of a selection screen, you could have the user type out a number instead, makes it slightly easier and feel less cryptic.
Cool cool. Adding this in 0.15.0

> You could have CSMark open up that HTML file automagically through Windows 10 and its preferred web browser.
This would require what I call "Platform Adaptive Code" but I'll see what I can do.
