### ISSUE TITLE
Feature request: Replace command system

### ISSUE THREAD

**Issue by sjoerd108** [CSMarkBenchmark/CSMark#9]
The current command system can be a hassle for people testing a wide variety of hardware, making it potentially tedious to navigate.

Possible solutions would be:

- A GUI version, tough this may be time consuming to implement.
- Replace the commands with numbers instead. For example ``please enter BENCH`` would become ``please enter 0`` This can speed things up drastically.
- Make an argument system so that people can pass the benchmark settings they want to the program. It would look like this: ``./CSMarkRedux  --BENCH_MULTI --WX12``

CSMark version: 0.16.2
OS: Arch Linux (Kernel 4.12.10-1-ARCH)

**Comment by AluminiumTech** [comment]
> A GUI version, tough this may be time consuming to implement.

This is coming soon. Although users will still be able to use the CLI if they wish to. The GUI version will just be a Shell which passes information to the CLI and then gets the information back from the CLI and displays it.

> Replace the commands with numbers instead. For example please enter BENCH would become please 
>  enter  0 This can speed things up drastically.

Alright. I'll add this to 0.17.0 . The old commands will still work but they won't be shown on startup.

> Make an argument system so that people can pass the benchmark settings they want to the program. 
>  It would look like this: ./CSMarkRedux --BENCH_MULTI --WX12

CSMark already has an [argument system](https://github.com/CSMarkBenchmark/CSMark/blob/master/docs/CommandLineArguments.md). If you'd like for me to improve upon it then I'll see what I can do.
